# Example configuration file for Nginx Proxy Manager Switcher
# Copy this file to config.yml and modify according to your setup

# --- Global Settings ---
# Path to the SQLite database file for storing service states.
sqlite_file: /data/database.db

# Directory where the final Nginx proxy configurations will be written.
nginx_conf_dir: /data/nginx/proxy_host

# Path for the checker script's log file.
log_file: /var/log/host_switcher.log

# --- Service Definitions ---
services:
  sso:
    domain: sso.smkn3singaraja.sch.id
    # The URL to check for service health. A 2xx status code means success.
    check: http://192.168.11.1:8000/up
    # Time between health checks when the service is UP.
    interval: 2s
    # Time to wait before retrying after a check has FAILED.
    error_delay: 5s
    # Upstream server to use if the health check succeeds.
    if_success:
      host: 192.168.11.1
      port: 8000
    # Fallback upstream server to use if the health check fails.
    if_failed:
      host: 192.168.13.1
      port: 80

  # Example: Website service
  website:
    domain: www.smkn3singaraja.sch.id
    check: http://192.168.20.5:80/health
    interval: 5s
    error_delay: 10s
    if_success:
      host: 192.168.20.5
      port: 80
    if_failed:
      host: 192.168.21.5
      port: 80

  # Example: API service
  api:
    domain: api.smkn3singaraja.sch.id
    check: http://192.168.30.10:3000/health
    interval: 3s
    error_delay: 8s
    if_success:
      host: 192.168.30.10
      port: 3000
    if_failed:
      host: 192.168.30.11
      port: 3000
