# Example configuration file for Nginx Proxy Manager Switcher
# Copy this file to config.yml and modify according to your setup

# --- Global Settings ---
# Path to the SQLite database file for storing service states.
sqlite_file: /data/database.db

# Directory where the final Nginx proxy configurations will be written.
nginx_conf_dir: /data/nginx/proxy_host

# Path for the checker script's log file.
log_file: /var/log/host_switcher.log

# Command to reload Nginx configuration (optional, defaults to '/usr/sbin/nginx -s reload')
# Examples:
# nginx_refresh_cmd: /usr/sbin/nginx -s reload
# nginx_refresh_cmd: /usr/local/bin/nginx -s reload
# nginx_refresh_cmd: docker exec nginx-container nginx -s reload
# nginx_refresh_cmd: systemctl reload nginx

# Directory for storing proxy_host backups (optional, defaults to './backups')
# Examples:
# backup_dir: ./backups
# backup_dir: /var/backups/nginx-proxy-manager
# backup_dir: /data/backups
backup_dir: ./backups

# snapshot_dir: /data/snapshots
snapshot_dir: ./snapshots

# snapshot_number: 3  # Use specific snapshot number (optional)
# force_snapshot: true  # Force creation of new snapshot from current state (optional)

# --- Service Definitions ---
services:
  sso:
    domain: sso.smkn3singaraja.sch.id
    # The URL to check for service health. A 2xx status code means success.
    check: http://192.168.11.1:8000/up
    # Time between health checks when the service is UP.
    interval: 2s
    # Time to wait before retrying after a check has FAILED.
    error_delay: 5s
    # Number of retry attempts before marking as failed (optional, defaults to 3)
    retries: 3
    # Upstream server to use if the health check succeeds (optional).
    # If not provided, the application will use the original configuration from the database.
    # if_success:
    #   host: 192.168.11.1
    #   port: 8000
    # Fallback upstream server to use if the health check fails.
    if_failed:
      host: 192.168.13.1
      port: 80
      scheme: http # Optional: http or https

  # Example: Website service
  website:
    domain: www.smkn3singaraja.sch.id
    check: http://192.168.20.5:80/health
    interval: 5s
    error_delay: 10s
    retries: 2 # Less retries for faster detection
    # if_success is optional - will use original config from database
    if_failed:
      host: 192.168.21.5
      port: 80
      scheme: http # Optional: http or https

  # Example: API service
  api:
    domain: api.smkn3singaraja.sch.id
    check: http://192.168.30.10:3000/health
    interval: 3s
    error_delay: 8s
    retries: 5 # More retries for critical service
    # if_success is optional - will use original config from database
    if_failed:
      host: 192.168.30.11
      port: 3000
      scheme: https # Optional: http or https
